--- #YAML:1.0
name:               WWW-Offline-Toolkit
version:            0.01
abstract:           Perl module for offline website creation.
author:
    - Tom Kirchner <tom@tkirchner.com>
license:            unknown
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
build_requires:
    ExtUtils::MakeMaker:  0
requires:
    Data::Dumper:       1.0
    File::Find:         1.0
    Parse::RecDescent:  1.0
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.56
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
